### PR TITLE
Revamp

### PR DESCRIPTION
**Pull request by 3kh0**
I made the website look better and more clean.

Preview: https://gosub.3kh0.repl.co/

### CODE REVIEW

**Comment by bigfatbird** [comment]
Clean design, also looks nice.

Why did you remove the normalizer, and put the css back in the html?

**Comment by 3kh0** [comment]
Normalizer messed up some of the styles and increased loading time by a tiny bit.

Having the CSS in a different file makes no sense as there is a very small amount of it, and it made loading a tiny bit longer.

**Comment by bigfatbird** [comment]
Isn't the normalizer especially there to not mess up the styles, but to... well normalize them?

**Comment by jaytaph** [comment]
Lgtm. After meege i'll deploy it but thar would be tomorrow morning (CEST). Might even setup a rsync job in the ci

**Comment by 3kh0** [comment]
@bigfatbird, The normalizer made it so the padding is all wonky and incorrect.

**Pull request merged**
